# Introduction to SQL Queries

# Pair Programming Exercise for DSE5002
Kat Wifvat September 23, 2026

Updated 4/6/2026

We will connect to the chinook database and work through some *queries*

The slang term for this is *pulling data from the database*

These are queries made to a single table, we will see later how to join tables together and create subqueries

The commands used in queries are:

SELECT --specify the variables or columns required

FROM--specify the table to obtain data from 

LIMIT-- restrict the number of lines returned to a desired total N

WHERE-- this is a filtering function carried out on row elements,  we can use AND, OR and NOT within the Where

ORDER BY-- This is a sorting function,   it can sortascending or descending, and we can sort on multiple variables

GROUP BY--this is a grouping function

HAVING--Having is a filtering operation on group members

MAX(), MIN(), AVG(), SUM(), COUNT() are aggregating functions used with GROUP BY,  


These are the available commands in SQL that we use in combination to create queries.  We can do the same types of data slicing, sorting, filtering ect that we do in R or Python dataframes in SQL.

While the names are different, the actions appear in the TidyVerse library in R and in the Polars library in Python.   Polars is an alternative to Pandas and has some advantages over Pandas with working with large data sets,   and it's query system is almost identical to SQL,  which is an advantage.

# Source material

"Learning SQL", Beaulieu,  O'Reilly 2005

https://www.sqlitetutorial.net/   - explains queries using the chinook database, albeit in the SQLite database system.  The SELECT system used for queries is pretty standard for most SQL databases,   the other aspects and commands seem to be a bit more variable from one server program to another.

That said, there are minor differences in variable names between the chinook database in postgres and the tutorial for SQlite,   watch for underscores and pluralization (track vs tracks, etc).   I have fixed all the examples shown here.

Please be sure you have the chinook.db file in the same directory as this python notebook

# Connect to the Chinook Database

and figure out what we have in it


Set up the required libraries

In [1]:
#import psycopg2
import sqlalchemy

# we will want Pandas for the data frame structure

import pandas as pd

In [2]:
#connect to the Chinook Database in SQLite using
# the sqlalchemy library

# make sure the chinook.db database file is in your current working directory

engine=sqlalchemy.create_engine("sqlite:///chinook.db")

In [3]:
# sqlalchemy has an "Inspector Tool" that 
# will allow you to "look" at the datbase,   I'm using
# it here to check to be sure the connection is working

# I don't know much about the inspector, I typically just use SQL commands
# to do what I want, but the inspector may be useful at times.  Google it for
# more info

inspector = sqlalchemy.inspect(engine)

# Get all table names in the default schema
print(inspector.get_table_names())

['albums', 'artists', 'customers', 'employees', 'genres', 'invoice_items', 'invoices', 'media_types', 'playlist_track', 'playlists', 'ranks', 'tracks']

In [4]:
# Don't run this code block

# this is from an earlier version of this course that used the postgress 
# database

# Notice that the only difference in the Python code is the way we connect to 
# the database


# Alter this to reflect your username and password,   this is for postgres on the same machine

# if you are using the default installation of Postgress and the databases for the course DSE5002, this 
# command should work fine for the user bob whose password is pwd1

#engine=sqlalchemy.create_engine('postgresql://bob:pwd1@localhost:5432/chinook')

In [5]:
pd.__version__

'3.0.3'

# what tables do we have

We can use a SELECT command to look for the table_name values in a built-in database called information_schema,  in a table called tables.  
This is a database and table that are built into postgres to hold information.   It holds a lot of info, but our table names are all in the first 15 lines


Notice that this command does pretty much what the "inspector" command above does, but uses just SQL

In [6]:
pd.read_sql_query("SELECT name FROM sqlite_master",engine)

                                 name
0                              albums
1                     sqlite_sequence
2                             artists
3                           customers
4                           employees
5                              genres
6                            invoices
7                       invoice_items
8                         media_types
9                           playlists
10                     playlist_track
11  sqlite_autoindex_playlist_track_1
12                             tracks
13                  IFK_AlbumArtistId
14           IFK_CustomerSupportRepId
15              IFK_EmployeeReportsTo
16              IFK_InvoiceCustomerId
17           IFK_InvoiceLineInvoiceId
18             IFK_InvoiceLineTrackId
19           IFK_PlaylistTrackTrackId
20                   IFK_TrackAlbumId
21                   IFK_TrackGenreId
22               IFK_TrackMediaTypeId
23                       sqlite_stat1
24                              ranks
25                    ManagementRoles

In [7]:
# Looking at the customer table, but only first 5 rows

pd.read_sql_query("SELECT * FROM customers LIMIT 5",engine)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,0171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [8]:
#restrict this to only CustomerId, first and last names


pd.read_sql_query("SELECT CustomerId, FirstName, LastName FROM customers LIMIT 8",engine)

   CustomerId  FirstName     LastName
0           1       Luís    Gonçalves
1           2     Leonie       Köhler
2           3   François     Tremblay
3           4      Bjørn       Hansen
4           5  František  Wichterlová
5           6     Helena         Holý
6           7     Astrid       Gruber
7           8       Daan      Peeters

# *QUESTION/ACTION*

Figure out what the table "invoices" looks like,  display the first 5 lines of it so you can see the content

In [9]:
pd.read_sql_query("--add your query here ---",engine)

ResourceClosedError: This result object does not return rows. It has been closed automatically.

# *Question/Action*

Show the variables CustomerId,  BillingCountry and total for the first 12 lines of invoice

# Ordering or Sorting Results

In [10]:
pd.read_sql_query("SELECT * FROM tracks ORDER BY Milliseconds LIMIT 12",engine)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,2461,É Uma Partida De Futebol,200,1,1,Samuel Rosa,1071,38747,0.99
1,168,Now Sports,18,1,4,NaN,4884,161266,0.99
2,170,A Statistic,18,1,4,NaN,6373,211997,0.99
3,178,Oprah,18,1,4,NaN,6635,224313,0.99
4,3304,Commercial 1,258,1,17,L. Muggerud,7941,319888,0.99
5,172,The Real Problem,18,1,4,NaN,11650,387360,0.99
6,3310,Commercial 2,258,1,17,L. Muggerud,21211,850698,0.99
7,2241,Bossa,184,1,17,NaN,29048,967098,0.99
8,1086,Casinha Feliz,85,1,10,Gilberto Gil,32287,1039615,0.99
9,246,Mateus Enter,24,1,7,Chico Science,33149,1103013,0.99
10,975,Deixa Entrar,78,1,7,NaN,33619,1095012,0.99
11,2797,Homem Primata (Vinheta),224,1,4,Titãs,34168,1124909,0.99

In [11]:
# reversed order sort

# add DESC to sort descending, ASC to sort ascending

pd.read_sql_query("SELECT * FROM tracks ORDER BY Milliseconds DESC LIMIT 12",engine)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,2820,Occupation / Precipice,227,3,19,None,5286953,1054423946,1.99
1,3224,Through a Looking Glass,229,3,21,None,5088838,1059546140,1.99
2,3244,"Greetings from Earth, Pt. 1",253,3,20,None,2960293,536824558,1.99
3,3242,The Man With Nine Lives,253,3,20,None,2956998,577829804,1.99
4,3227,"Battlestar Galactica, Pt. 2",253,3,20,None,2956081,521387924,1.99
5,3226,"Battlestar Galactica, Pt. 1",253,3,20,None,2952702,541359437,1.99
6,3243,Murder On the Rising Star,253,3,20,None,2935894,551759986,1.99
7,3228,"Battlestar Galactica, Pt. 3",253,3,20,None,2927802,554509033,1.99
8,3248,Take the Celestra,253,3,20,None,2927677,512381289,1.99
9,3239,Fire In Space,253,3,20,None,2926593,536784757,1.99
10,3232,The Long Patrol,253,3,20,None,2925008,513122217,1.99
11,3235,The Magnificent Warriors,253,3,20,None,2924716,570152232,1.99

In [12]:
# sort by two variables

pd.read_sql_query("SELECT * FROM tracks ORDER BY composer ASC, milliseconds DESC LIMIT 12",engine)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,2820,Occupation / Precipice,227,3,19,None,5286953,1054423946,1.99
1,3224,Through a Looking Glass,229,3,21,None,5088838,1059546140,1.99
2,3244,"Greetings from Earth, Pt. 1",253,3,20,None,2960293,536824558,1.99
3,3242,The Man With Nine Lives,253,3,20,None,2956998,577829804,1.99
4,3227,"Battlestar Galactica, Pt. 2",253,3,20,None,2956081,521387924,1.99
5,3226,"Battlestar Galactica, Pt. 1",253,3,20,None,2952702,541359437,1.99
6,3243,Murder On the Rising Star,253,3,20,None,2935894,551759986,1.99
7,3228,"Battlestar Galactica, Pt. 3",253,3,20,None,2927802,554509033,1.99
8,3248,Take the Celestra,253,3,20,None,2927677,512381289,1.99
9,3239,Fire In Space,253,3,20,None,2926593,536784757,1.99
10,3232,The Long Patrol,253,3,20,None,2925008,513122217,1.99
11,3235,The Magnificent Warriors,253,3,20,None,2924716,570152232,1.99

# *Question/Action*

Sort invoices by BillingCity (ascending) and total purchase (descending),  show the InvoiceId, BillingCity and total

In [ ]:
pd.read_sql_query("--add your query here ---",engine)

# Distinct

Selects only the unique values of a variable

In [13]:
# look at the Distinct cities in our customer list

pd.read_sql_query("""SELECT DISTINCT city 
                    FROM customers
                    ORDER BY city
                    LIMIT 20;"""
                     ,engine)

            City
0      Amsterdam
1      Bangalore
2         Berlin
3       Bordeaux
4         Boston
5       Brasília
6       Brussels
7       Budapest
8   Buenos Aires
9        Chicago
10    Copenhagen
11     Cupertino
12         Delhi
13         Dijon
14        Dublin
15    Edinburgh
16      Edmonton
17    Fort Worth
18     Frankfurt
19       Halifax

# *Question/Action*

Find the list of distinct artists listed in Track,   sort them

# Where

Where is a filter that allows us to filter out only the rows that meet some desired condition.  

Notice that the select command itself allows us to control the columns show, Where works on the rows

# Comparison Operators

=,   !=,  <, >, >=, <=                 *Note equality is a single equal sign in postgres "="

# Logical Operators

AND, NOT, OR

# Other tests

ALL- 1 if all expressions are 1

ANY- 1 if any expressions is 1

BETWEEN- tests for a range of values

IN- comparison to a list of values

LIKE- used on strings, if they match a pattern

In [14]:
# we can select as specific album id for the tracks 

pd.read_sql_query("""SELECT name, milliseconds,bytes,AlbumId
                     FROM tracks
                     WHERE AlbumId=6""", engine)

                           Name  Milliseconds     Bytes  AlbumId
0             All I Really Want        284891   9375567        6
1               You Oughta Know        249234   8196916        6
2                       Perfect        188133   6145404        6
3             Hand In My Pocket        221570   7224246        6
4             Right Through You        176117   5793082        6
5                      Forgiven        300355   9753256        6
6                     You Learn        239699   7824837        6
7                Head Over Feet        267493   8758008        6
8                     Mary Jane        280607   9163588        6
9                        Ironic        229825   7598866        6
10               Not The Doctor        227631   7604601        6
11                      Wake Up        293485   9703359        6
12  You Oughta Know (Alternate)        491885  16008629        6

In [15]:
# we can select as specific album id for the tracks and restrict to relatively short tracks

pd.read_sql_query("""SELECT name, milliseconds,bytes,AlbumId
                     FROM tracks
                     WHERE AlbumId=6 AND milliseconds<250000""", engine)

                Name  Milliseconds    Bytes  AlbumId
0    You Oughta Know        249234  8196916        6
1            Perfect        188133  6145404        6
2  Hand In My Pocket        221570  7224246        6
3  Right Through You        176117  5793082        6
4          You Learn        239699  7824837        6
5             Ironic        229825  7598866        6
6     Not The Doctor        227631  7604601        6

In [ ]:
# *Question/Action*

Find out how many invoices totals where over 25

# LIKE

In [16]:
# The Like operator,  allows partial text matching

# note the use of the doubled percent signs %%
# also note that this is case sensitive

pd.read_sql_query("""SELECT name, AlbumId, composer 
                     FROM tracks
                     WHERE composer LIKE '%%Smith%%'""",engine)

,Name,AlbumId,Composer
0,Restless and Wild,3,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D..."
1,Princess of the Dawn,3,Deaffy & R.A. Smith-Diesel
2,Killing Floor,19,Adrian Smith
3,Machine Men,19,Adrian Smith
4,2 Minutes To Midnight,95,Adrian Smith/Bruce Dickinson
...,...,...,...
92,Savior,195,Anthony Kiedis/Chad Smith/Flea/John Frusciante
93,Dancing Barefoot,234,Ivan Kral/Patti Smith
94,Take the Box,322,Luke Smith
95,What Is It About Men,322,"Delroy ""Chris"" Cooper, Donovan Jackson, Earl C..."
96,Amy Amy Amy (Outro),322,"Astor Campbell, Delroy ""Chris"" Cooper, Donovan..."

# *Question/Action*

Use the LIKE function to find all the invoice entries from Ireland

be sure to use LIKE,   the = test would work here too, but practice using LIKE

# IN

Tests for membership in a list

Also filtering out one AC/DC album using AND NOT combined with LIKE

In [17]:
pd.read_sql_query("""SELECT
                        name,
                        AlbumId,
                        MediaTypeId
                    FROM
                        tracks
                    WHERE
                        MediaTypeId IN (2, 3) AND NOT(name LIKE '%%Wall%%');""",engine)

                                               Name  AlbumId  MediaTypeId
0                                   Fast As a Shark        3            2
1                                 Restless and Wild        3            2
2                              Princess of the Dawn        3            2
3                             Welcome to the Jungle       90            2
4                                      It's So Easy       90            2
..                                              ...      ...          ...
444               There's No Place Like Home, Pt. 2      261            3
445               There's No Place Like Home, Pt. 3      261            3
446  Band Members Discuss Tracks from "Revelations"      271            3
447                                  Branch Closing      251            3
448                                      The Return      251            3

[449 rows x 3 columns]

# AND

In [18]:
pd.read_sql_query("""SELECT
                      BillingAddress,
                      BillingCity,
                      total
                    FROM
                      invoices
                    WHERE
                      BillingCity= 'New York'
                    AND total > 5
                    ORDER BY
                      total;""",engine)

  BillingAddress BillingCity  Total
0   627 Broadway    New York   5.94
1   627 Broadway    New York   8.91
2   627 Broadway    New York  13.86

In [19]:
pd.read_sql_query("""SELECT * FROM invoices LIMIT 5""",engine)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,1.98
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,NaN,Norway,0171,3.96
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,NaN,Belgium,1000,5.94
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86

# OR

Using AND and OR together

In [20]:
pd.read_sql_query("""SELECT
                      BillingAddress,
                      BillingCity,
                      total
                    FROM
                      invoices
                    WHERE
                      (BillingCity= 'New York' OR BillingCity= 'Chicago')
                    AND total > 5
                    ORDER BY
                      total;""",engine)

          BillingAddress BillingCity  Total
0           627 Broadway    New York   5.94
1  162 E Superior Street     Chicago   5.94
2  162 E Superior Street     Chicago   7.96
3  162 E Superior Street     Chicago   8.91
4           627 Broadway    New York   8.91
5           627 Broadway    New York  13.86
6  162 E Superior Street     Chicago  15.86

# BETWEEN

Looks for a range of values

In [21]:
pd.read_sql_query("""SELECT
                        InvoiceId,
                        BillingAddress,
                        total
                    FROM
                        invoices
                    WHERE
                        total BETWEEN 14.91 and 18.86    
                    ORDER BY
                        total; """,engine)

   InvoiceId                        BillingAddress  Total
0        193                      Berger Straße 10  14.91
1        103                 162 E Superior Street  15.86
2        208                      Ullevålsveien 14  15.86
3        306                         Klanova 9/506  16.86
4        313                      68, Rue Jouvence  16.86
5         88                       Calle Lira, 198  17.91
6         89  Rotenturmstraße 4, 1010 Innere Stadt  18.86
7        201                 319 N. Frances Street  18.86

In [22]:
#NOT BETWEEN
#
# excluding a range


pd.read_sql_query("""SELECT
                        InvoiceId,
                        BillingAddress,
                        total
                    FROM
                        invoices
                    WHERE
                        total NOT BETWEEN 1 and 20    
                    ORDER BY
                        total; """,engine)

    InvoiceId                            BillingAddress  Total
0           6                          Berger Straße 10   0.99
1          13                 1600 Amphitheatre Parkway   0.99
2          20                            110 Raeburn Pl   0.99
3          27                            5112 48 Street   0.99
4          34                          Praça Pio X, 119   0.99
5          41                        C/ San Bernardo 85   0.99
6          48                    796 Dundas Street West   0.99
7          55                           Grétrystraat 63   0.99
8          62                          3 Chatham Street   0.99
9          69                     319 N. Frances Street   0.99
10         76                          Ullevålsveien 14   0.99
11         83                    9, Place Louis Barthou   0.99
12         90                          801 W 4th Street   0.99
13        104                       Barbarossastraße 19   0.99
14        111                           1 Microsoft Way   0.99
15        118                         421 Bourke Street   0.99
16        125                        Rua da Assunção 53   0.99
17        132                              Qe 7 Bloco G   0.99
18        139                               Celsiusg. 9   0.99
19        146                          230 Elgin Street   0.99
20        153                       Sønder Boulevard 51   0.99
21        160                    Via Degli Scipioni, 43   0.99
22        167                       2211 W Berry Street   0.99
23        174                             Klanova 9/506   0.99
24        181                          68, Rue Jouvence   0.99
25        188                          120 S Orange Ave   0.99
26        195           Av. Brigadeiro Faria Lima, 2170   0.99
27        209                              627 Broadway   0.99
28        216                        307 Macacha Güemes   0.99
29        223  Rua dos Campeões Europeus de Viena, 4350   0.99
30        230                            8210 111 ST NW   0.99
31        237                         202 Hoxton Street   0.99
32        244                     194A Chain Lake Drive   0.99
33        251                 Rua Dr. Falcão Filho, 155   0.99
34        258                     Lijnbaansgracht 120bg   0.99
35        265                           1033 N Park Ave   0.99
36        272                             Rilská 3174/6   0.99
37        279                           Porthaninkatu 9   0.99
38        286                           69 Salem Street   0.99
39        293                   Theodor-Heuss-Straße 34   0.99
40        300                            8, Rue Hanovre   0.99
41        314                           Calle Lira, 198   0.99
42        321                        Tauentzienstraße 8   0.99
43        328                       700 W Pender Street   0.99
44        335                              113 Lupus St   0.99
45        342                        696 Osborne Street   0.99
46        349                        Av. Paulista, 2022   0.99
47        356                              Ordynacka 10   0.99
48        363                               302 S 700 E   0.99
49        370      Rotenturmstraße 4, 1010 Innere Stadt   0.99
50        377                         Erzsébet krt. 58.   0.99
51        384                     162 E Superior Street   0.99
52        391                         1498 rue Bélanger   0.99
53        398                       11, Place Bellecour   0.99
54        405                      541 Del Medio Avenue   0.99
55         96                         Erzsébet krt. 58.  21.86
56        194                          3 Chatham Street  21.86
57        299                       2211 W Berry Street  23.86
58        404                             Rilská 3174/6  25.86

In [23]:
# shut down the engine to close the connection

engine.dispose()